### ISSUE TITLE
add request config variable to force cache

### ISSUE THREAD

**Issue by csanquer** [guzzle/cache-subscriber#22]
It would be nice to have a kind of request config parameters to override  and force caching even if the server doesn't send cache-control reponse header.

it might be config parameters like `cache.force` and `cache.ttl`

**Comment by edmondscommerce** [comment]
FYI this is how I achieved an always on cache:

``` php
        
        $guzzle = new GuzzleHttp\Client(array('defaults' => $guzzle_options));

        GuzzleHttp\Subscriber\Cache\CacheSubscriber::attach(
            $guzzle,
            array(
                'storage' => new GuzzleHttp\Subscriber\Cache\CacheStorage(
                    new FilesystemCache('/path/to/cache/storage/')
                ),
                'can_cache' => function () {
                    return true;
                }
            )
        );

        $emitter = $guzzle->getEmitter();
        $emitter->on(
            'complete',
            function (\GuzzleHttp\Event\CompleteEvent $event) {
                $response = $event->getResponse();
                $response->setHeader('Cache-Control', '');
            },
            'first'
        );
```

I've put the fully qualified stuff in to make it more portable but you probably want to tidy that up

**Comment by csanquer** [comment]
I made a PR #53  for overriding response max-age TTL

**Comment by alcohol** [comment]
Possibly another solution for this is to add the correct headers yourself? I wrote a small client for an API that does not return caching headers but does expect clients to cache responses. I accomplished it with another simple subscriber: [HeaderSubscriber.php](https://github.com/alcohol/eve-xmlapi/blob/master/source/Client/Subscriber/HeaderSubscriber.php)

**Comment by mtdowling** [comment]
Rob,

Your solution for adding cache headers is exactly what I had in mind. And it doesn't require an update to the caching logic.

**Comment by EdwardIII** [comment]
For anyone else that stumbles across this issue who had the same problem:

I spent some time figuring out why this solution didn't work for me. It turned out that even the header being present in the response caused canCacheResponse to return false.

I fixed this by simply changing:

                $response->setHeader('Cache-Control', '');

To:

                $response->removeHeader('Cache-Control');

**Comment by cadavre** [comment]
For all struggling with answer for this, you can use `GreedyCacheStrategy` which doesn't take headers into consideration and allows you to specify `ttl` by yourself.
