### ISSUE TITLE
Support for Guzzle 4?

### ISSUE THREAD

**Issue by dmyers** [guzzle/cache-subscriber#50]
I've been trying to figure out how to handle caching on Guzzle 4 and it seems the cache detection stuff was pulled out of 3 and into this and this package's original tag says it requires 5, is there any way to use it or recommendation on 4?

The reason I'm using 4 is due to Laravel which recommends using it. http://laravel.com/docs/5.0/mail#configuration

**Comment by mtdowling** [comment]
Guzzle 4 is no longer supported. V5 is basically v5, but with a few more abstractions. Any reason you can't upgrade?
