### ISSUE TITLE
CacheStorage contains abstract code

### ISSUE THREAD

**Issue by shadowhand** [guzzle/cache-subscriber#51]
From what I can tell, the current `CacheStorage` class contains a lot of code that is useful for any `CacheStorageInterface`, not just Doctrine cache. I think a cache storage provider should only need to required to define these methods:
- `setCache($key, array $content)` (or maybe `$content` should already be serialized?)
- `getCache($key)`
- `deleteCache($key)`

Everything else should be defined in an abstract class that can be overloaded as necessary, or provided by the main `CacheSubscriber`.

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but I'm going to close this since this repo has been EOL for a while now.
