### ISSUE TITLE
Vary header not considerend

### ISSUE THREAD

**Issue by KingCrunch** [guzzle/cache-subscriber#52]
I am not completely done with debugging, but it looks like the Vary headers is never considered because of some case mismatch, see https://github.com/guzzle/cache-subscriber/blob/ff265668cf95d6c4a583526082f36980e4513f49/src/CacheStorage.php#L138
I tried some variations and as far as I can see Guzzle always normalizes the header to `Vary` (uppercase `V`).

Update:
Actually the same issue appears some lines later https://github.com/guzzle/cache-subscriber/blob/ff265668cf95d6c4a583526082f36980e4513f49/src/CacheStorage.php#L231
The `strtolower()` cause the headers doesn't match anymore.

Update2:
It's possible, that this is already fixed in the latest `master`. I'm still investigating.

**Comment by alcohol** [comment]
Can you share your code that shows the contrary? From what I can gather, it should work just fine. Also, internally Guzzle uses lowercase header names. Also the link you posted in your update is comparing the headers mentioned in vary, it's not looking at the actual vary header itself there.

**Comment by solcre** [comment]
I'm having the same problem as @KingCrunch headers are saved with uppercase "Vary" and it won't match against "vary" in https://github.com/guzzle/cache-subscriber/blob/master/src/CacheStorage.php#L138

Any solution for this?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but I'm going to close this since this repo has been EOL for a while now.
