### ISSUE TITLE
CacheStorage adds entries with no TTL

### ISSUE THREAD

**Issue by gunnarlium** [guzzle/cache-subscriber#58]
I'm actually using Guzzle3 with the DefautlCacheStorage and Redis as a backend. The number of items kept growing, which lead me track down possible causes, and the implementation looks similar in Guzzle 5.

What I'm wondering is why this line doesn't set a TTL:
https://github.com/guzzle/cache-subscriber/blob/master/src/CacheStorage.php#L86

As I read the code, whenever something is added to the cache, a new entry is added without a TTL. Is there a reason for why TTL is not set here?

**Comment by pschultz** [comment]
We just had issues for the same reason. @mtdowling, care to comment?

**Comment by GrahamCampbell** [comment]
Thanks for getting in touch, but I'm going to close this since this repo has been EOL for a while now.
