### ISSUE TITLE
First stable release

### ISSUE THREAD

**Issue by pkruithof** [guzzle/cache-subscriber#62]
I would like to upgrade my project to Guzzle 5, as it's been released for some time now. However I'm using the [`CachePlugin`](https://github.com/guzzle/guzzle3/blob/master/src/Guzzle/Plugin/Cache/CachePlugin.php) from version 3. The warning at the bottom of the readme doesn't give a lot of confidence:

> This is a WIP update for Guzzle 5+. It hasn't been tested and is in active development. Expect bugs and breaks.

Is there an expected release date for a stable version of this subscriber? If not, what needs to be done to get there? This is blocking my Guzzle upgrade, and I read version 3 will be EOL soon.

**Comment by bmancone** [comment]
@pkruithof, I upgraded to Guzzle5 and I use the cache-subscriber.

Apart from issue #59 for which I did a PR (#60) (still waiting for review from @mtdowling), I don't have any major issues in production.

**Comment by GrahamCampbell** [comment]
I suspect the first major release will come after guzzle 6?

**Comment by pkruithof** [comment]
Guzzle 6? Why a new major release so soon? Will there be BC breaks in this version again?

**Comment by pkruithof** [comment]
In any case, if the plugin is relatively stable now, can we at least get a new version? There's been a lot of commits since the 0.1.0 release: https://github.com/guzzle/cache-subscriber/compare/0.1.0...master

**Comment by pkruithof** [comment]
ping @mtdowling

**Comment by Kevinrob** [comment]
I am interested too!
