### ISSUE TITLE
Support for guzzle 6

### ISSUE THREAD

**Issue by bmancone** [guzzle/cache-subscriber#63]
Is a support for guzzle 6 planned ?

**Comment by bmancone** [comment]
I just started to write a [middleware](https://github.com/bmancone/guzzle-cache-middleware) for guzzle 6 if anyone want to join..

**Comment by onema** [comment]
:+1:  Yes please!

**Comment by Kevinrob** [comment]
For information, I have already begin to write a cache middleware for Guzzle6. https://github.com/Kevinrob/guzzle-cache-middleware
