### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by coolblue-koen** [guzzle/cache-subscriber#65]
Can you please create a new release? As the current tag is almost a year old. Thanks!

**Comment by bmancone** [comment]
Hello !

Could you please tag a new version (even if it's only compatible with guzzle 5) ? The #60 PR was merged 4 months ago and fixes a critical issue.

Thanks !

**Comment by lucascherifi** [comment]
Yes it could be great! Currently, I have to add a commit hash in all of my composer.json files to be able to use it..

Thanks a lot !

**Comment by lucascherifi** [comment]
(@mtdowling)

**Comment by bmancone** [comment]
Same here @lucascherifi, I have to use my own fork.

**Comment by bashilbers** [comment]
+1 here, we need that defaultTtl goodness!

**Comment by Progi1984** [comment]
Poke @jeremeamia @jeskew @Nyholm @sagikazarmark @Tobion

**Comment by Nyholm** [comment]
Hey. 
I would be happy to tag a new release as soon as possible. Before a release can be tagged, we need a change log that describes the changes between 0.1.0 and the new 0.2.0. 

Could someone make that PR and ping me in it?

**Comment by Progi1984** [comment]
@Nyholm I'm on it ;)

**Comment by Progi1984** [comment]
@Nyholm Pull Request : https://github.com/guzzle/cache-subscriber/pull/75

**Comment by Nyholm** [comment]
Thank you for the PR. 
Im happy to finally close this issue. 

I just tagged 0.2.0: https://github.com/guzzle/cache-subscriber/releases/tag/0.2.0

**Comment by Progi1984** [comment]
@Nyholm Thank you for your time :tada: 

:warning:  Packagist is not updated : https://packagist.org/packages/guzzlehttp/cache-subscriber

**Comment by Nyholm** [comment]
I dont have permissions to update this. We've pinged @mtdowling. Just waiting for his response.

**Comment by Nyholm** [comment]
There you go. Mark helped us

**Comment by Progi1984** [comment]
@Nyholm Perfect. Thank you (from me & @prestashop Core Team)
